### ISSUE TITLE
Add ability to update entity's fields

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#15]
If you look inside `JsonDatabaseService.updateEntityFields` method, you will find that we get fields only from `incomeEntity`, but not from it's superclass. Since we don't know how many inheritance levels we have for specific entity, consider adding fields from all superclasses to processing.

**Comment by shashinadya** [comment]
Began doing this task.

**Comment by shashinadya** [comment]
[PR40](https://github.com/shashinadya/code-practice/pull/40)

**Comment by shashinadya** [comment]
[PR40](https://github.com/shashinadya/code-practice/pull/40) merged to master.
