### ISSUE TITLE
Add ability to create new table file if table size is reached 10mb.

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#16]
Working with a large table file can bring performance and stability issues, consider creating a new file with the same name plus number at the end if current table is reached 10mb when adding new record. So, if original table file has name `StudentTable`, let's name new files like `StudentTable1`, `StudentTable2` etc.

**Comment by shashinadya** [comment]
Began doing this task.

**Comment by shashinadya** [comment]
[PR35](https://github.com/shashinadya/code-practice/pull/35)
