### ISSUE TITLE
Change Id type in DatabaseService api.

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#17]
Change `Id` type in `DatabaseService.getById` method from generic type to `int` since we use `BaseEntity` as a superclass for all entities.

**Comment by shashinadya** [comment]
Started doing task

**Comment by shashinadya** [comment]
Finished task

**Comment by shashinadya** [comment]
PR: https://github.com/shashinadya/code-practice/pull/23

**Comment by shashinadya** [comment]
PR https://github.com/shashinadya/code-practice/pull/23 merged to master
