### ISSUE TITLE
Add REST Api layer to DatabaseService. 

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#18]
Add `REST Api` to your application. All methods from `DatabaseService` should be accessible from the `REST` enpoints. Use appropriate `HTTP` responces in both successful and unsuccessful `DatabaseService` operations execution.

**Comment by shashinadya** [comment]
[PR](https://github.com/shashinadya/code-practice/pull/25) merged to master

**Comment by shashinadya** [comment]
[PR41](https://github.com/shashinadya/code-practice/pull/41)

**Comment by shashinadya** [comment]
[PR41](https://github.com/shashinadya/code-practice/pull/41) merged to master.
