### ISSUE TITLE
Move DatabaseService to Maven subproject

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#20]
`Maven` provides opportunity to devide your project to modules, it can help you to isolate different logic parts from each other. Please investigate how to move your existing project to multi-module project.

**Comment by shashinadya** [comment]
[PR47](https://github.com/shashinadya/code-practice/pull/47)

**Comment by shashinadya** [comment]
[PR47](https://github.com/shashinadya/code-practice/pull/47) merged to master.
