### ISSUE TITLE
Remove all relationships between entities in DatabaseService.

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#21]
We want to store only independent entities to do not overcomplicate logic, so please remove any references between existing entities.

**Comment by shashinadya** [comment]
Started task

**Comment by shashinadya** [comment]
PR: https://github.com/shashinadya/code-practice/pull/24

**Comment by shashinadya** [comment]
PR https://github.com/shashinadya/code-practice/pull/24 merged to master
