### ISSUE TITLE
Add offset and limit to DatabaseService.getAllRecordsFromTable method

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#22]
In case when we work with huge amount of records, we might want to use `offset` and `limit` parameters in `DatabaseService.getAllRecordsFromTable` method. Please create an overload version of `DatabaseService.getAllRecordsFromTable` method where this parameters are presented. Please use the following rules:

- if no `offset` and `limit` parameters provided, use original `DatabaseService.getAllRecordsFromTable` method.
- if `offset` or `limit` parameters are not valid (e.g. value < 0, or `limit` - `offset` > 200), throw `ValidationException`.
- if `offset` or `limit` parameters are valid, use new `DatabaseService.getAllRecordsFromTable` method.

Also please use default values for original method `DatabaseService.getAllRecordsFromTable` method. Let's make `offset`=0 and `limit`=100. Please put this default values into `properties` file.

**Comment by shashinadya** [comment]
Began doing this task.

**Comment by shashinadya** [comment]
[PR33](https://github.com/shashinadya/code-practice/pull/33)

**Comment by shashinadya** [comment]
[PR33](https://github.com/shashinadya/code-practice/pull/33) merged to master.
