### ISSUE TITLE
Return 404 if id provided when creating new entity

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#27]
Our sistem fills `id` automatically, so we need to ignore `id` value provided by user. Let's return `404` with proper message when user provides `id` when creating a new record in the database.

**Comment by shashinadya** [comment]
Began doing this task

**Comment by shashinadya** [comment]
Added 404 returning [PR30](https://github.com/shashinadya/code-practice/pull/30)

**Comment by shashinadya** [comment]
[PR30](https://github.com/shashinadya/code-practice/pull/30) merged to master
