### ISSUE TITLE
Make tests more reliable with BeforeEach and AfterEach methods.

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#31]
To make database tests more predictable and stable, please add `BeforeEach` and `AfterEach` methods in JsonDatabaseServiceTest.

Consider doing the following:

- Reinitialize `student` variables and `jsonDatabaseService` in `BeforeEach` method.
- Remove `Student` table in  `AfterEach` method. Since we use another table in only one test, let's do not include it in `AfterEach`. Instead, wrap `removeAllRecordsResetIdCounterCheckTest` with `try-finally` block and remove `Course` table inside `finally` block.

**Comment by shashinadya** [comment]
Began doing this task.

**Comment by shashinadya** [comment]
[PR32](https://github.com/shashinadya/code-practice/pull/32)

**Comment by shashinadya** [comment]
[PR32](https://github.com/shashinadya/code-practice/pull/32) merged to master.
