### ISSUE TITLE
Add logger configuration for tests

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#34]
Now our tests use logger configuration from the main code, so we put errors from tests into main logs. This can be confusing when checking application health status, so let's create another logger config for tests where we only put INFO logs in console.

**Comment by shashinadya** [comment]
Began doing this task.

**Comment by shashinadya** [comment]
[PR39](https://github.com/shashinadya/code-practice/pull/39)

**Comment by shashinadya** [comment]
[PR39](https://github.com/shashinadya/code-practice/pull/39) merged to master.
