### ISSUE TITLE
FileDatabaseExceptionHandler class refactoring

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#42]
Set error status message using `HttpStatus` enum message. Please check `HttpStatus` source code and see how you can use `message` field.

**Comment by shashinadya** [comment]
[PR46](https://github.com/shashinadya/code-practice/pull/46)

**Comment by shashinadya** [comment]
[PR46](https://github.com/shashinadya/code-practice/pull/46) merged to master.
