### ISSUE TITLE
Generate Swagger API documentation

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#43]
Please generate Swagger API documentation for REST endpoints.

**Comment by shashinadya** [comment]
[PR45](https://github.com/shashinadya/code-practice/pull/45)

**Comment by mishashin** [comment]
[PR58](https://github.com/shashinadya/code-practice/pull/58)

**Comment by shashinadya** [comment]
[PR58](https://github.com/shashinadya/code-practice/pull/58) merged to master.
