### ISSUE TITLE
Change deleteTable implementation for Json database

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#51]
Currently, we have a different behaviour in `Json` and `Sql` databases in `deleteTable` method. Let's change `Json` database service to return true even if file does not exist. I think we need to catch `NoSuchFileException` **BEFORE** catching `IOException` and return `true`. Please check in Postman and write test.

**Comment by shashinadya** [comment]
[PR53](https://github.com/shashinadya/code-practice/pull/53)

**Comment by shashinadya** [comment]
[PR53](https://github.com/shashinadya/code-practice/pull/53) merged to master.
