### ISSUE TITLE
Add Prepared Statements to SqlDatabaseService

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#59]
Since we want to build reliable and secure application, let's replace usual statements with prepared statements to avoid of `SQL Injection` attack. Please modify the following methods:

- removeRecordFromTable
- addNewRecordToTable
- updateRecordInTable
- getById
- getByFilters

**Comment by shashinadya** [comment]
[PR65](https://github.com/shashinadya/code-practice/pull/65)

**Comment by shashinadya** [comment]
[PR65](https://github.com/shashinadya/code-practice/pull/65) merged to master.
