### ISSUE TITLE
Add ability to use connection pool in SqlDatabaseService

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#60]
Since opening new connection to a database is a very expensive operation, let's add ability to use connection pool.
Please don't use existing solutions since it's easy to implement your own implementation. Use `MysqlDataSource` as the pool provider.

**Comment by shashinadya** [comment]
[PR61](https://github.com/shashinadya/code-practice/pull/61)

**Comment by shashinadya** [comment]
[PR61](https://github.com/shashinadya/code-practice/pull/61) merged to master.
