### ISSUE TITLE
Modify getAllRecordsFromTable methods to avoid code duplication

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#64]
To avoid code duplication, please use common `SQL` query for both methods. Remove all code from `getAllRecordsFromTable` version where you don't have `limit` and `offset` parameters and just call overloaded method and provide `limit` from `settings` and `offset=0`.

**Comment by shashinadya** [comment]
[PR68](https://github.com/shashinadya/code-practice/pull/68)

**Comment by shashinadya** [comment]
[PR68](https://github.com/shashinadya/code-practice/pull/68) merged to master.
