### ISSUE TITLE
Remove resetting of entity id generator

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#66]
Let's do not reset `AUTO INCREMENT` and `entityIds` value in both `File` and `SQL` services to provide more clear history of operations.

So please do the following:

- remove resetting of auto increment from `addNewRecordToTable` in `SqlDatabaseService`;
- remove resetting of auto entityIds from `addNewRecordToTable` in `JsonDatabaseService`;
- remove resetting of auto entityIds from `removeAllRecordsFromTable` in `JsonDatabaseService`;

**Comment by shashinadya** [comment]
[PR69](https://github.com/shashinadya/code-practice/pull/69)

**Comment by shashinadya** [comment]
[PR69](https://github.com/shashinadya/code-practice/pull/69) merged to master.
