### ISSUE TITLE
Implement batch operations to add and remove records

### ISSUE THREAD

**Issue by mishashin** [shashinadya/code-practice#67]
Please implement 2 new menthods:

1. `<T extends BaseEntity> T addNewRecordsToTable(List<T> entity)`;
2. `boolean removeSpecificRecords(Class<? extends BaseEntity> entityClass, List<Integer> ids)`;

I expect that there won't be any significant changes in `JsonDatabaseService` comparing to single record adding/removing, but please make batches transactional in `SqlDatabaseService`. Also please identify if we need to add transactions in another already implemented methods.

**Comment by shashinadya** [comment]
[PR73](https://github.com/shashinadya/code-practice/pull/73)

**Comment by shashinadya** [comment]
[PR73](https://github.com/shashinadya/code-practice/pull/73) merged to master.
